### Create a question
POST http://127.0.0.1:5000/api/questions
Content-Type: application/json

{
    "name": "John Smith",
    "text": "This is a not that I hope works",
    "repo": "repo",
    "live": "live"
}

### View questions
GET http://127.0.0.1:5000/api/questions
Content-Type: application/json

### Edit a question


### Delete a question
DELETE http://127.0.0.1:5000/api/questions/608990cba163b218a682e33a
Content-Type: application/json